"""
Amazon US categories focused on CONSUMABLE/REPLENISHABLE products.
These are products customers buy repeatedly — high lifetime value.

Each subcategory includes:
  - volume: "high" | "medium" | "low" — general demand level on Amazon
  - competition: "high" | "medium" | "low" — how saturated the niche is
  - tip: short actionable advice for private label sellers
  - search_terms: real Amazon search keywords for this subcategory
"""

AMAZON_US_CATEGORIES = [
    {
        "id": "household",
        "name": "Household & Cleaning",
        "node": "15342811",
        "repurchase_weeks": 4,
        "tip": "Los productos de limpieza tienen alta lealtad de marca. Diferencia con ingredientes naturales, eco-friendly o aromas premium.",
        "subcategories": [
            {
                "id": "hh-laundry", "name": "Laundry Detergent & Supplies", "node": "15342821",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Marcas gigantes dominan. Enfoca en detergentes eco, para ropa de bebé, o para pieles sensibles.",
                "search_terms": ["laundry detergent", "laundry pods", "fabric softener", "stain remover"],
            },
            {
                "id": "hh-cleaning", "name": "All-Purpose Cleaners", "node": "15342811",
                "repurchase_weeks": 6, "volume": "high", "competition": "high",
                "tip": "Nicho saturado. Busca limpiadores especializados: para granito, acero inoxidable, o con ingredientes naturales.",
                "search_terms": ["all purpose cleaner", "multi surface cleaner", "natural cleaning spray"],
            },
            {
                "id": "hh-dish", "name": "Dish Soap & Dishwasher", "node": "15342801",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Dominio de grandes marcas. Oportunidad en jabones de platos naturales o pastillas eco para lavavajillas.",
                "search_terms": ["dish soap", "dishwasher pods", "dishwasher detergent"],
            },
            {
                "id": "hh-trash", "name": "Trash Bags & Liners", "node": "15342861",
                "repurchase_weeks": 3, "volume": "high", "competition": "medium",
                "tip": "Producto commodity. Compite en precio o diferencia con bolsas compostables/biodegradables.",
                "search_terms": ["trash bags", "garbage bags", "compostable trash bags", "kitchen bags"],
            },
            {
                "id": "hh-paper", "name": "Paper Towels & Tissues", "node": "15342851",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Logística compleja por volumen. Difícil competir con Subscribe & Save de grandes marcas.",
                "search_terms": ["paper towels", "facial tissues", "toilet paper"],
            },
            {
                "id": "hh-airfresh", "name": "Air Fresheners", "node": "3744271",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Buena oportunidad en aromas premium, sprays naturales con aceites esenciales, o eliminadores de olores especializados.",
                "search_terms": ["air freshener", "room spray", "odor eliminator", "car air freshener"],
            },
            {
                "id": "hh-sponge", "name": "Sponges & Scrubbers", "node": "15342841",
                "repurchase_weeks": 4, "volume": "medium", "competition": "low",
                "tip": "Nicho accesible. Esponjas ecológicas, cepillos de bambú, o packs multipropósito tienen espacio.",
                "search_terms": ["kitchen sponge", "scrub brush", "dish sponge", "cleaning sponge"],
            },
            {
                "id": "hh-wipes", "name": "Disinfectant Wipes", "node": "15342811",
                "repurchase_weeks": 3, "volume": "high", "competition": "medium",
                "tip": "Post-pandemia la demanda se mantuvo alta. Toallitas naturales o con aromas premium son oportunidad.",
                "search_terms": ["disinfectant wipes", "cleaning wipes", "antibacterial wipes"],
            },
        ],
    },
    {
        "id": "beauty",
        "name": "Beauty & Personal Care",
        "node": "3760911",
        "repurchase_weeks": 6,
        "tip": "Categoría masiva con espacio para marcas nicho. Ingredientes naturales, veganos y orgánicos son tendencia fuerte.",
        "subcategories": [
            {
                "id": "bp-shampoo", "name": "Shampoo & Conditioner", "node": "11057241",
                "repurchase_weeks": 6, "volume": "high", "competition": "high",
                "tip": "Nicho enorme pero saturado. Diferencia por tipo de cabello (rizado, fino), ingredientes (sin sulfatos, keratina).",
                "search_terms": ["shampoo", "conditioner", "sulfate free shampoo", "shampoo and conditioner set"],
            },
            {
                "id": "bp-bodywash", "name": "Body Wash & Shower Gel", "node": "11056281",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Body wash para hombres y body wash con ingredientes naturales tienen buen crecimiento.",
                "search_terms": ["body wash", "shower gel", "body wash for men", "moisturizing body wash"],
            },
            {
                "id": "bp-skincare", "name": "Face Moisturizer & Serum", "node": "11060451",
                "repurchase_weeks": 8, "volume": "high", "competition": "high",
                "tip": "Márgenes altos pero competencia feroz. Ingredientes como retinol, vitamina C, niacinamida siguen en auge.",
                "search_terms": ["face moisturizer", "face serum", "retinol cream", "vitamin c serum", "hyaluronic acid"],
            },
            {
                "id": "bp-deodorant", "name": "Deodorant & Antiperspirant", "node": "11056071",
                "repurchase_weeks": 6, "volume": "high", "competition": "medium",
                "tip": "Desodorantes naturales (sin aluminio) crecen rápido. Marca propia viable con buen branding.",
                "search_terms": ["deodorant", "natural deodorant", "antiperspirant", "deodorant for women"],
            },
            {
                "id": "bp-sunscreen", "name": "Sunscreen & Sun Care", "node": "11056171",
                "repurchase_weeks": 8, "volume": "high", "competition": "medium",
                "tip": "Demanda estacional pero constante. Protectores minerales y reef-safe son tendencia.",
                "search_terms": ["sunscreen", "sunscreen spf 50", "mineral sunscreen", "sunscreen for face"],
            },
            {
                "id": "bp-lotion", "name": "Body Lotion & Cream", "node": "11056201",
                "repurchase_weeks": 6, "volume": "high", "competition": "medium",
                "tip": "Lociones especializadas (para eczema, piel seca extrema, con colágeno) tienen menos competencia.",
                "search_terms": ["body lotion", "body cream", "moisturizing lotion", "hand cream"],
            },
            {
                "id": "bp-handsoap", "name": "Hand Soap & Sanitizer", "node": "3760931",
                "repurchase_weeks": 3, "volume": "high", "competition": "medium",
                "tip": "Jabones de manos con aromas premium o ingredientes naturales se diferencian bien.",
                "search_terms": ["hand soap", "hand sanitizer", "foaming hand soap", "liquid hand soap"],
            },
            {
                "id": "bp-lipcheek", "name": "Lip Balm & Lip Care", "node": "11058431",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Producto pequeño con alto margen. Packs de labiales naturales, orgánicos o con SPF son oportunidad.",
                "search_terms": ["lip balm", "lip moisturizer", "chapstick", "lip oil"],
            },
        ],
    },
    {
        "id": "oralcare",
        "name": "Oral Care",
        "node": "10079992011",
        "repurchase_weeks": 8,
        "tip": "Categoría dominada por grandes marcas en lo básico, pero nichos como whitening y natural tienen espacio.",
        "subcategories": [
            {
                "id": "oc-toothpaste", "name": "Toothpaste", "node": "10079992011",
                "repurchase_weeks": 6, "volume": "high", "competition": "high",
                "tip": "Colgate y Crest dominan. Oportunidad en pastas naturales, de carbón activado, o para sensibilidad.",
                "search_terms": ["toothpaste", "whitening toothpaste", "charcoal toothpaste", "natural toothpaste"],
            },
            {
                "id": "oc-mouthwash", "name": "Mouthwash & Rinse", "node": "10079992011",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Enjuagues sin alcohol y naturales están creciendo. Menos dominación de marca vs. pasta dental.",
                "search_terms": ["mouthwash", "alcohol free mouthwash", "whitening mouthwash"],
            },
            {
                "id": "oc-floss", "name": "Dental Floss & Picks", "node": "10079992011",
                "repurchase_weeks": 4, "volume": "medium", "competition": "low",
                "tip": "Producto simple con buena recompra. Hilo dental de carbón, eco-friendly o water flossers accesorios.",
                "search_terms": ["dental floss", "floss picks", "water flosser", "charcoal dental floss"],
            },
            {
                "id": "oc-whitening", "name": "Teeth Whitening", "node": "10079992011",
                "repurchase_weeks": 8, "volume": "high", "competition": "medium",
                "tip": "Alto margen y alta demanda. Strips, pens y kits LED son los formatos más populares.",
                "search_terms": ["teeth whitening strips", "teeth whitening kit", "whitening pen", "teeth whitening"],
            },
            {
                "id": "oc-brush", "name": "Toothbrush Heads & Refills", "node": "10079992011",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Cabezales compatibles con Oral-B y Sonicare son un nicho de recompra constante.",
                "search_terms": ["toothbrush replacement heads", "electric toothbrush heads", "bamboo toothbrush"],
            },
        ],
    },
    {
        "id": "vitamins",
        "name": "Vitamins & Supplements",
        "node": "3764441",
        "repurchase_weeks": 4,
        "tip": "Categoría en auge constante. Requiere cumplir regulaciones FDA. Gummies y formatos innovadores crecen rápido.",
        "subcategories": [
            {
                "id": "vit-multi", "name": "Multivitamins", "node": "3764441",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Mercado masivo. Diferencia por demografía: mujeres 50+, prenatal, niños, atletas.",
                "search_terms": ["multivitamins", "multivitamin for women", "multivitamin for men", "gummy vitamins"],
            },
            {
                "id": "vit-protein", "name": "Protein Powder & Shakes", "node": "6973663011",
                "repurchase_weeks": 3, "volume": "high", "competition": "high",
                "tip": "Nicho masivo y competido. Oportunidad en proteínas veganas, colágeno, o sabores únicos.",
                "search_terms": ["protein powder", "whey protein", "vegan protein powder", "protein shake"],
            },
            {
                "id": "vit-probiotic", "name": "Probiotics & Digestive", "node": "3764441",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Crecimiento constante. Probióticos para mujeres, para niños, o con prebióticos incluidos.",
                "search_terms": ["probiotics", "probiotics for women", "digestive enzymes", "prebiotics"],
            },
            {
                "id": "vit-collagen", "name": "Collagen & Beauty Supplements", "node": "3764441",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Tendencia en auge. Colágeno en polvo, péptidos, y combinaciones con biotina/vitamina C.",
                "search_terms": ["collagen powder", "collagen peptides", "biotin", "hair skin nails vitamins"],
            },
            {
                "id": "vit-omega", "name": "Fish Oil & Omega", "node": "3764441",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Mercado estable. Omega-3 vegano (de algas) y versiones sin sabor a pescado son oportunidad.",
                "search_terms": ["fish oil", "omega 3", "krill oil", "vegan omega 3"],
            },
            {
                "id": "vit-pre", "name": "Pre-Workout & Energy", "node": "6973663011",
                "repurchase_weeks": 3, "volume": "high", "competition": "medium",
                "tip": "Audiencia leal con alta recompra. Fórmulas sin estimulantes y para mujeres tienen menos competencia.",
                "search_terms": ["pre workout", "pre workout powder", "energy supplements", "bcaa"],
            },
            {
                "id": "vit-melatonin", "name": "Melatonin & Sleep Aids", "node": "3764441",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Demanda creciente. Gummies de melatonina, combinaciones con magnesio y L-teanina.",
                "search_terms": ["melatonin", "melatonin gummies", "sleep aid", "magnesium for sleep"],
            },
            {
                "id": "vit-vitd", "name": "Vitamin D & Immunity", "node": "3764441",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Post-pandemia sigue en alta demanda. Vitamina D3+K2, zinc, elderberry como combinaciones.",
                "search_terms": ["vitamin d3", "vitamin d", "elderberry", "zinc supplements", "vitamin c"],
            },
            {
                "id": "vit-ashwa", "name": "Ashwagandha & Adaptogens", "node": "3764441",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Nicho en crecimiento rápido. Ashwagandha, rhodiola, lion's mane son los adaptógenos más buscados.",
                "search_terms": ["ashwagandha", "ashwagandha gummies", "lions mane", "mushroom supplement"],
            },
            {
                "id": "vit-creatine", "name": "Creatine & Performance", "node": "6973663011",
                "repurchase_weeks": 3, "volume": "high", "competition": "medium",
                "tip": "Creatina monohidratada domina. Formatos en gummies y creatina para mujeres son oportunidad nueva.",
                "search_terms": ["creatine", "creatine monohydrate", "creatine gummies", "creatine powder"],
            },
        ],
    },
    {
        "id": "grocery",
        "name": "Grocery & Pantry",
        "node": "16310101",
        "repurchase_weeks": 2,
        "tip": "Alta recompra pero márgenes ajustados por peso/envío. Productos premium, orgánicos o especializados son mejor camino.",
        "subcategories": [
            {
                "id": "gr-coffee", "name": "Coffee & Coffee Pods", "node": "16318401",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Mercado enorme. Café orgánico single-origin, pods compatibles Keurig con sabores únicos.",
                "search_terms": ["coffee pods", "k cups", "ground coffee", "organic coffee", "espresso pods"],
            },
            {
                "id": "gr-tea", "name": "Tea & Herbal", "node": "16318401",
                "repurchase_weeks": 3, "volume": "medium", "competition": "medium",
                "tip": "Tés funcionales (detox, para dormir, para digestión) tienen margen y menos competencia que café.",
                "search_terms": ["green tea", "herbal tea", "matcha powder", "chamomile tea", "detox tea"],
            },
            {
                "id": "gr-snacks", "name": "Snack Bars & Protein Bars", "node": "16322721",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Muy competido. Barras keto, veganas, o para nichos específicos (diabéticos, sin gluten) tienen espacio.",
                "search_terms": ["protein bars", "snack bars", "granola bars", "keto bars", "energy bars"],
            },
            {
                "id": "gr-spices", "name": "Spices & Seasonings", "node": "16310231",
                "repurchase_weeks": 8, "volume": "medium", "competition": "medium",
                "tip": "Productos livianos con buen margen. Mezclas de especias únicas, rubs para BBQ, o sets de regalo.",
                "search_terms": ["spices", "seasoning", "spice set", "bbq rub", "everything bagel seasoning"],
            },
            {
                "id": "gr-sauces", "name": "Sauces & Condiments", "node": "16310231",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Salsas picantes artesanales, salsas asiáticas, y aderezos keto tienen audiencia leal.",
                "search_terms": ["hot sauce", "bbq sauce", "soy sauce", "salad dressing", "keto sauce"],
            },
            {
                "id": "gr-honey", "name": "Honey & Natural Sweeteners", "node": "16310231",
                "repurchase_weeks": 8, "volume": "medium", "competition": "medium",
                "tip": "Miel manuka, miel cruda local, y edulcorantes como monk fruit tienen premium pricing.",
                "search_terms": ["honey", "manuka honey", "raw honey", "monk fruit sweetener", "stevia"],
            },
            {
                "id": "gr-nuts", "name": "Nuts & Trail Mix", "node": "16322721",
                "repurchase_weeks": 2, "volume": "high", "competition": "medium",
                "tip": "Alta recompra. Trail mix con sabores únicos o frutos secos premium (macadamia, pistachos).",
                "search_terms": ["mixed nuts", "trail mix", "almonds", "cashews", "pistachios"],
            },
            {
                "id": "gr-superfoods", "name": "Superfoods & Powders", "node": "16310101",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Matcha, spirulina, cacao en polvo. Producto liviano con márgenes altos y audiencia health-conscious.",
                "search_terms": ["matcha powder", "spirulina powder", "cacao powder", "chia seeds", "acai powder"],
            },
        ],
    },
    {
        "id": "baby",
        "name": "Baby Consumables",
        "node": "165796011",
        "repurchase_weeks": 2,
        "tip": "Padres son compradores leales y no escatiman en calidad. Productos orgánicos y eco-friendly premium funcionan.",
        "subcategories": [
            {
                "id": "bb-diapers", "name": "Diapers", "node": "166764011",
                "repurchase_weeks": 1, "volume": "high", "competition": "high",
                "tip": "Dominado por Pampers, Huggies. Pañales eco/bambú tienen nicho premium pero logística difícil.",
                "search_terms": ["diapers", "baby diapers", "newborn diapers", "bamboo diapers"],
            },
            {
                "id": "bb-wipes", "name": "Baby Wipes", "node": "166764011",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Alta recompra pero dominado por grandes marcas. Toallitas orgánicas, sin fragancia, o de agua pura.",
                "search_terms": ["baby wipes", "water wipes", "organic baby wipes", "sensitive baby wipes"],
            },
            {
                "id": "bb-formula", "name": "Baby Formula & Food", "node": "166777011",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Regulación estricta (FDA). Comida orgánica para bebés en pouches es más accesible que fórmula.",
                "search_terms": ["baby formula", "baby food", "baby food pouches", "organic baby food"],
            },
            {
                "id": "bb-lotion", "name": "Baby Lotion & Wash", "node": "166772011",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Productos naturales para piel sensible de bebé. Sets de baño y kits de regalo tienen buen margen.",
                "search_terms": ["baby lotion", "baby wash", "baby shampoo", "baby bath", "baby oil"],
            },
            {
                "id": "bb-diaper-cream", "name": "Diaper Rash Cream", "node": "166764011",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Menos dominación de marca grande. Cremas orgánicas o con calendula tienen oportunidad.",
                "search_terms": ["diaper rash cream", "diaper cream", "baby butt paste", "zinc oxide cream"],
            },
            {
                "id": "bb-teething", "name": "Teething & Pacifiers", "node": "166859011",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Mordedores de silicona, chupones premium, y geles naturales para dentición. Nicho accesible.",
                "search_terms": ["teething toys", "baby pacifier", "teething gel", "silicone teether"],
            },
        ],
    },
    {
        "id": "pets",
        "name": "Pet Consumables",
        "node": "2619533011",
        "repurchase_weeks": 3,
        "tip": "Dueños de mascotas gastan generosamente. Productos premium, naturales y funcionales crecen rápido.",
        "subcategories": [
            {
                "id": "pt-dogfood", "name": "Dog Food & Kibble", "node": "2975312011",
                "repurchase_weeks": 3, "volume": "high", "competition": "high",
                "tip": "Dominado por grandes marcas. Comida para razas específicas, grain-free, o fresca es oportunidad.",
                "search_terms": ["dog food", "dry dog food", "grain free dog food", "puppy food"],
            },
            {
                "id": "pt-dogtreats", "name": "Dog Treats & Chews", "node": "2975312011",
                "repurchase_weeks": 2, "volume": "high", "competition": "medium",
                "tip": "Treats naturales, de un solo ingrediente, y dental chews tienen margen y buena recompra.",
                "search_terms": ["dog treats", "dog chews", "dental chews for dogs", "bully sticks", "dog jerky"],
            },
            {
                "id": "pt-catfood", "name": "Cat Food & Litter", "node": "2975241011",
                "repurchase_weeks": 2, "volume": "high", "competition": "high",
                "tip": "Arena para gatos tiene costos de envío altos. Comida húmeda premium y arena natural son opciones.",
                "search_terms": ["cat food", "cat litter", "wet cat food", "clumping cat litter"],
            },
            {
                "id": "pt-cattreats", "name": "Cat Treats", "node": "2975241011",
                "repurchase_weeks": 3, "volume": "medium", "competition": "medium",
                "tip": "Treats de atún liofilizado, lickable treats, y catnip son populares y livianos para enviar.",
                "search_terms": ["cat treats", "cat snacks", "lickable cat treats", "catnip", "freeze dried cat treats"],
            },
            {
                "id": "pt-supplements", "name": "Pet Vitamins & Supplements", "node": "2619533011",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Suplementos para articulaciones, probióticos para perros, y aceite de salmón son los más vendidos.",
                "search_terms": ["pet supplements", "dog joint supplement", "dog probiotics", "salmon oil for dogs"],
            },
            {
                "id": "pt-grooming", "name": "Pet Shampoo & Grooming", "node": "2619533011",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Shampoos para razas específicas, deshedding, o con avena. Nicho accesible con buen margen.",
                "search_terms": ["dog shampoo", "pet grooming", "deshedding shampoo", "cat shampoo"],
            },
            {
                "id": "pt-waste", "name": "Poop Bags & Cleanup", "node": "2619533011",
                "repurchase_weeks": 3, "volume": "high", "competition": "low",
                "tip": "Producto simple, alta recompra. Bolsas biodegradables y dispensadores premium.",
                "search_terms": ["dog poop bags", "biodegradable dog bags", "pet waste bags"],
            },
        ],
    },
    {
        "id": "autocare",
        "name": "Auto Care Consumables",
        "node": "15718271",
        "repurchase_weeks": 8,
        "tip": "Audiencia mayormente masculina, leal a productos que funcionan. Detailing es el sub-nicho con más crecimiento.",
        "subcategories": [
            {
                "id": "ac-wash", "name": "Car Wash Soap", "node": "15718271",
                "repurchase_weeks": 8, "volume": "medium", "competition": "medium",
                "tip": "Chemical Guys domina pero hay espacio para fórmulas especializadas (ceramic, foam cannon).",
                "search_terms": ["car wash soap", "car shampoo", "foam cannon soap", "ceramic car wash"],
            },
            {
                "id": "ac-wax", "name": "Car Wax & Polish", "node": "15718271",
                "repurchase_weeks": 12, "volume": "medium", "competition": "medium",
                "tip": "Spray wax y ceramic coating son tendencia vs. ceras tradicionales. Mayor margen en fórmulas premium.",
                "search_terms": ["car wax", "car polish", "ceramic coating", "spray wax", "scratch remover"],
            },
            {
                "id": "ac-interior", "name": "Interior Cleaner & Wipes", "node": "15718271",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Limpiadores de cuero, protectores de tablero, y toallitas para pantallas táctiles. Menos competencia.",
                "search_terms": ["car interior cleaner", "leather cleaner", "dashboard cleaner", "car cleaning wipes"],
            },
            {
                "id": "ac-freshener", "name": "Car Air Freshener", "node": "15718271",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Aromas premium tipo cologne, difusores de ventilación, y eliminadores de olores funcionan bien.",
                "search_terms": ["car air freshener", "car freshener vent clip", "car scent", "car odor eliminator"],
            },
            {
                "id": "ac-towels", "name": "Microfiber Towels & Detailing", "node": "15718271",
                "repurchase_weeks": 8, "volume": "medium", "competition": "low",
                "tip": "Toallas de microfibra en packs, kits de detailing, y accesorios. Producto liviano y buen margen.",
                "search_terms": ["microfiber towels", "car detailing kit", "microfiber cloth", "drying towel"],
            },
        ],
    },
    {
        "id": "wellness",
        "name": "Wellness & Essential Oils",
        "node": "3760911",
        "repurchase_weeks": 6,
        "tip": "Audiencia principalmente femenina y wellness-oriented. Productos experienciales con buena oportunidad de marca.",
        "subcategories": [
            {
                "id": "wl-essential", "name": "Essential Oils", "node": "3760911",
                "repurchase_weeks": 8, "volume": "high", "competition": "medium",
                "tip": "Sets de aceites esenciales, mezclas para dormir/estrés, y roll-ons listos para usar.",
                "search_terms": ["essential oils", "essential oil set", "lavender oil", "peppermint oil", "tea tree oil"],
            },
            {
                "id": "wl-candles", "name": "Scented Candles", "node": "3734261",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Velas de soya, mechas de madera, aromas únicos. Sets de regalo y suscripción son tendencia.",
                "search_terms": ["scented candles", "soy candles", "candle set", "aromatherapy candles"],
            },
            {
                "id": "wl-diffuser", "name": "Diffuser Oils & Refills", "node": "3760911",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Aceites para difusor, recambios de reed diffuser, y mezclas para nebulizadores.",
                "search_terms": ["diffuser oil", "reed diffuser refill", "diffuser essential oils", "room diffuser"],
            },
            {
                "id": "wl-bath", "name": "Bath Bombs & Salts", "node": "11056281",
                "repurchase_weeks": 4, "volume": "medium", "competition": "medium",
                "tip": "Bath bombs en sets de regalo son best sellers. Sales de epsom y sales de baño con CBD.",
                "search_terms": ["bath bombs", "bath salts", "epsom salt", "shower steamers", "bubble bath"],
            },
            {
                "id": "wl-herbal", "name": "Herbal Tea & Wellness Drinks", "node": "16318401",
                "repurchase_weeks": 3, "volume": "medium", "competition": "medium",
                "tip": "Tés funcionales (digestión, sleep, detox) y mezclas de superfoods en polvo.",
                "search_terms": ["herbal tea", "wellness tea", "turmeric tea", "ginger tea", "detox tea"],
            },
            {
                "id": "wl-incense", "name": "Incense & Sage", "node": "3734261",
                "repurchase_weeks": 4, "volume": "medium", "competition": "low",
                "tip": "Incienso, salvia para smudging, palo santo. Nicho espiritual/wellness con audiencia leal.",
                "search_terms": ["incense sticks", "sage smudge stick", "palo santo", "incense cones"],
            },
        ],
    },
    {
        "id": "haircare",
        "name": "Hair Care & Styling",
        "node": "11057241",
        "repurchase_weeks": 6,
        "tip": "Alta recompra y lealtad de marca. Productos para texturas específicas (rizado, afro, fino) tienen menos competencia.",
        "subcategories": [
            {
                "id": "hc-treatment", "name": "Hair Masks & Treatments", "node": "11057241",
                "repurchase_weeks": 6, "volume": "high", "competition": "medium",
                "tip": "Mascarillas de keratina, aceite de argán, y tratamientos reparadores. Alto margen.",
                "search_terms": ["hair mask", "hair treatment", "keratin treatment", "argan oil hair"],
            },
            {
                "id": "hc-oil", "name": "Hair Oil & Serum", "node": "11057241",
                "repurchase_weeks": 8, "volume": "high", "competition": "medium",
                "tip": "Aceites para cabello (argán, ricino, rosemary) y serums anti-frizz son best sellers constantes.",
                "search_terms": ["hair oil", "hair serum", "rosemary oil for hair", "castor oil", "argan oil"],
            },
            {
                "id": "hc-styling", "name": "Hair Gel & Styling", "node": "11057241",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Geles y pomadas para hombres, cremas para rizar, y spray texturizante.",
                "search_terms": ["hair gel", "pomade", "hair wax", "curl cream", "texturizing spray"],
            },
            {
                "id": "hc-growth", "name": "Hair Growth & Loss", "node": "11057241",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Biotina, minoxidil, y sueros de crecimiento. Alta recompra y disposición a pagar premium.",
                "search_terms": ["hair growth serum", "hair growth oil", "minoxidil", "biotin for hair", "hair loss treatment"],
            },
            {
                "id": "hc-color", "name": "Hair Color & Root Touch-Up", "node": "11057241",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Root touch-up sprays, tintes semi-permanentes, y color depositing shampoos.",
                "search_terms": ["hair color", "root touch up", "hair dye", "semi permanent hair color"],
            },
        ],
    },
    {
        "id": "mensgrooming",
        "name": "Men's Grooming",
        "node": "3760911",
        "repurchase_weeks": 6,
        "tip": "Mercado en crecimiento acelerado. Hombres cada vez compran más productos de cuidado personal premium.",
        "subcategories": [
            {
                "id": "mg-beard", "name": "Beard Oil & Care", "node": "3760911",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Aceites, bálsamos y kits para barba. Sets de regalo y suscripción funcionan bien.",
                "search_terms": ["beard oil", "beard balm", "beard grooming kit", "beard wash"],
            },
            {
                "id": "mg-shave", "name": "Shaving Cream & Aftershave", "node": "3760911",
                "repurchase_weeks": 6, "volume": "medium", "competition": "medium",
                "tip": "Cremas de afeitar artesanales, aftershave sin alcohol, y kits premium de afeitado.",
                "search_terms": ["shaving cream", "aftershave", "shave gel", "shaving soap"],
            },
            {
                "id": "mg-razors", "name": "Razor Blades & Refills", "node": "3760911",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Cuchillas compatibles con Gillette son un nicho de recompra constante. Safety razors crecen.",
                "search_terms": ["razor blades", "razor refills", "safety razor blades", "disposable razors"],
            },
            {
                "id": "mg-cologne", "name": "Men's Body Spray & Cologne", "node": "3760911",
                "repurchase_weeks": 8, "volume": "high", "competition": "medium",
                "tip": "Body sprays y fragancias asequibles tipo 'dupes' de marcas luxury tienen alta demanda.",
                "search_terms": ["mens cologne", "body spray for men", "mens fragrance", "mens deodorant spray"],
            },
        ],
    },
    {
        "id": "feminine",
        "name": "Feminine Care",
        "node": "3777891",
        "repurchase_weeks": 4,
        "tip": "Categoría con alta lealtad y recompra mensual garantizada. Productos orgánicos y eco-friendly crecen fuerte.",
        "subcategories": [
            {
                "id": "fm-pads", "name": "Pads & Liners", "node": "3777891",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Grandes marcas dominan. Oportunidad en toallas orgánicas, de algodón, y reutilizables.",
                "search_terms": ["feminine pads", "panty liners", "organic pads", "overnight pads"],
            },
            {
                "id": "fm-tampons", "name": "Tampons", "node": "3777891",
                "repurchase_weeks": 4, "volume": "high", "competition": "high",
                "tip": "Tampones orgánicos de algodón crecen vs. tradicionales. Aplicadores plant-based.",
                "search_terms": ["tampons", "organic tampons", "tampons regular", "tampons variety pack"],
            },
            {
                "id": "fm-cups", "name": "Menstrual Cups & Discs", "node": "3777891",
                "repurchase_weeks": 24, "volume": "medium", "competition": "low",
                "tip": "No es alta recompra pero alto margen. Copas menstruales, discos, y ropa interior period.",
                "search_terms": ["menstrual cup", "menstrual disc", "period underwear", "reusable pads"],
            },
            {
                "id": "fm-intimate", "name": "Intimate Wash & Care", "node": "3777891",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Jabones íntimos pH balanceado, toallitas íntimas, y probióticos femeninos. Nicho creciente.",
                "search_terms": ["feminine wash", "intimate wash", "feminine wipes", "ph balance wash"],
            },
        ],
    },
    {
        "id": "health",
        "name": "Health & First Aid",
        "node": "3760931",
        "repurchase_weeks": 8,
        "tip": "Productos esenciales con demanda constante. Regulación importante — asegura cumplimiento FDA/OTC.",
        "subcategories": [
            {
                "id": "hl-bandages", "name": "Bandages & First Aid", "node": "3760931",
                "repurchase_weeks": 8, "volume": "medium", "competition": "medium",
                "tip": "Kits de primeros auxilios, vendas especializadas (hidrogel, para ampollas), y tape médico.",
                "search_terms": ["bandages", "first aid kit", "band aids", "medical tape", "gauze pads"],
            },
            {
                "id": "hl-pain", "name": "Pain Relief & Patches", "node": "3760931",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Parches de menthol, cremas para dolor muscular, y TENS pads de repuesto.",
                "search_terms": ["pain relief patches", "icy hot", "muscle rub", "tens pads", "lidocaine patches"],
            },
            {
                "id": "hl-allergy", "name": "Allergy & Sinus Relief", "node": "3760931",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Spray nasal salino, tiras nasales, y purificadores nasales. Demanda estacional pero recurrente.",
                "search_terms": ["allergy relief", "nasal spray", "nasal strips", "sinus relief", "neti pot"],
            },
            {
                "id": "hl-thermometer", "name": "Thermometer & Health Monitors", "node": "3760931",
                "repurchase_weeks": 12, "volume": "medium", "competition": "low",
                "tip": "No es alta recompra pero accesorios sí: puntas de termómetro, tiras de test, lancetas.",
                "search_terms": ["thermometer", "blood pressure monitor", "pulse oximeter", "test strips"],
            },
        ],
    },
    {
        "id": "kitchen",
        "name": "Kitchen Consumables",
        "node": "289756",
        "repurchase_weeks": 4,
        "tip": "Productos de uso diario que se agotan. Enfoque eco-friendly y premium funciona bien aquí.",
        "subcategories": [
            {
                "id": "kt-wrap", "name": "Food Wrap & Storage Bags", "node": "289756",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Bolsas reutilizables de silicona, beeswax wraps, y bolsas al vacío. Eco es tendencia fuerte.",
                "search_terms": ["food storage bags", "beeswax wrap", "vacuum seal bags", "reusable bags", "plastic wrap"],
            },
            {
                "id": "kt-filters", "name": "Coffee Filters & Water Filters", "node": "289756",
                "repurchase_weeks": 4, "volume": "medium", "competition": "low",
                "tip": "Filtros de café para pour-over, filtros de agua de repuesto (Brita, PUR), y filtros de nevera.",
                "search_terms": ["coffee filters", "water filter", "brita filter replacement", "pour over filter"],
            },
            {
                "id": "kt-parchment", "name": "Parchment Paper & Baking", "node": "289756",
                "repurchase_weeks": 6, "volume": "medium", "competition": "low",
                "tip": "Papel pergamino, moldes de silicona reutilizables, y air fryer liners. Nicho accesible.",
                "search_terms": ["parchment paper", "air fryer liners", "silicone baking mat", "cupcake liners"],
            },
            {
                "id": "kt-disposable", "name": "Disposable Plates & Cutlery", "node": "289756",
                "repurchase_weeks": 4, "volume": "high", "competition": "medium",
                "tip": "Platos y cubiertos biodegradables/compostables para eventos. Packs bulk y sets temáticos.",
                "search_terms": ["disposable plates", "paper plates", "compostable plates", "plastic utensils", "paper cups"],
            },
        ],
    },
    {
        "id": "office",
        "name": "Office Supplies",
        "node": "1064954",
        "repurchase_weeks": 6,
        "tip": "Productos de oficina tienen demanda B2B y B2C constante. Marcas genéricas compiten bien en precio.",
        "subcategories": [
            {
                "id": "of-ink", "name": "Printer Ink & Toner", "node": "1064954",
                "repurchase_weeks": 6, "volume": "high", "competition": "medium",
                "tip": "Cartuchos compatibles de terceros son un negocio enorme. Recompra constante y alto margen.",
                "search_terms": ["printer ink", "toner cartridge", "ink cartridges", "compatible ink"],
            },
            {
                "id": "of-labels", "name": "Labels & Shipping Supplies", "node": "1064954",
                "repurchase_weeks": 4, "volume": "medium", "competition": "low",
                "tip": "Etiquetas de envío, etiquetas compatibles con Dymo/Zebra, y cintas de embalaje.",
                "search_terms": ["shipping labels", "thermal labels", "packing tape", "label maker refills"],
            },
            {
                "id": "of-paper", "name": "Copy Paper & Notebooks", "node": "1064954",
                "repurchase_weeks": 8, "volume": "high", "competition": "high",
                "tip": "Papel de impresora es commodity. Cuadernos especializados (planner, dotted, bullet journal) tienen margen.",
                "search_terms": ["copy paper", "printer paper", "notebook", "planner", "legal pads"],
            },
            {
                "id": "of-pens", "name": "Pens & Writing Supplies", "node": "1064954",
                "repurchase_weeks": 8, "volume": "medium", "competition": "medium",
                "tip": "Sets de plumas, highlighters, y marcadores para pizarra. Packs multipropósito para oficina.",
                "search_terms": ["pens", "gel pens", "highlighters", "dry erase markers", "sharpie"],
            },
        ],
    },
]


# Focused on high-repurchase consumable niches
POPULAR_NICHES = [
    # Household & Cleaning
    "laundry detergent",
    "dish soap",
    "all purpose cleaner",
    "trash bags",
    "paper towels",
    "air freshener",
    "fabric softener",
    "disinfectant wipes",
    "cleaning sponges",
    # Beauty & Personal Care
    "body wash",
    "shampoo",
    "conditioner",
    "hand soap",
    "body lotion",
    "deodorant",
    "sunscreen",
    "face moisturizer",
    "lip balm",
    # Oral Care
    "toothpaste",
    "mouthwash",
    "teeth whitening strips",
    "dental floss",
    "bamboo toothbrush",
    # Vitamins & Supplements
    "protein powder",
    "multivitamins",
    "collagen powder",
    "probiotics",
    "fish oil",
    "pre workout",
    "creatine",
    "melatonin gummies",
    "ashwagandha",
    "vitamin d3",
    "elderberry",
    # Hair Care
    "hair oil",
    "hair growth serum",
    "keratin treatment",
    "curl cream",
    "rosemary oil for hair",
    # Grocery
    "coffee pods",
    "green tea",
    "protein bars",
    "honey",
    "hot sauce",
    "spices seasoning",
    "matcha powder",
    "mixed nuts",
    # Baby
    "baby wipes",
    "diapers",
    "diaper cream",
    "baby lotion",
    "teething toys",
    # Pets
    "dog treats",
    "cat treats",
    "dog food",
    "cat litter",
    "pet supplements",
    "dog poop bags",
    "dog shampoo",
    # Auto
    "car wash soap",
    "car air freshener",
    "ceramic coating",
    "microfiber towels",
    # Men's Grooming
    "beard oil",
    "shaving cream",
    "mens cologne",
    "safety razor blades",
    # Feminine Care
    "organic tampons",
    "feminine wash",
    "menstrual cup",
    # Wellness
    "essential oils",
    "scented candles",
    "bath bombs",
    "incense sticks",
    "shower steamers",
    # Health
    "first aid kit",
    "pain relief patches",
    "nasal strips",
    # Kitchen
    "beeswax wrap",
    "coffee filters",
    "air fryer liners",
    "parchment paper",
    # Office
    "printer ink",
    "shipping labels",
    "gel pens",
]
